### ISSUE TITLE
Lint R and Julia code

### ISSUE THREAD

**Issue by BenKaehler** [BenKaehler/q2-makarsa#53]
Python code is linted but R and Julia has not been.

**Comment by IsaacTowers** [comment]
Would a tool like [JuliaFormatter](https://domluna.github.io/JuliaFormatter.jl/dev/) be appropriate for the Julia code? There is also [Clean.jl](https://github.com/KwatMDPhD/Clean.jl) and [Lint.jl](https://github.com/tonyhffong/Lint.jl).

**Comment by IsaacTowers** [comment]
This issue can be closed now.

**Comment by BenKaehler** [comment]
Closed by #73
