### ISSUE TITLE
node IDs do not correspond to feature IDs

### ISSUE THREAD

**Issue by nbokulich** [BenKaehler/q2-makarsa#80]
when putting in #78 and #79 I decided to try using various makarsa outputs with other QIIME 2 actions to test the new functionality.

The outputs of `louvain-communities` did not look quite like what I expected. I had understood that the node map would map features to modules... but the node and module IDs are both arbitrary IDs. This prevents the node map from having useful applications, e.g., to annotate or collapse features based on module identity.

@BenKaehler @rhernandvel **is this expected?** Shouldn't node IDs correspond to feature IDs? Are the feature IDs being replaced by arbitrary node IDs in `louvain-communities`, or are these the node labels in the input `Network`?

To reproduce: 

Using the outputs from the readme tutorial, this action will show you the node and module IDs:
```
qiime metadata tabulate \
        --m-input-file node-map.qza \
        --o-visualization node-map.qzv
```

and this action fails, because the node IDs do not actually correspond to feature IDs:
```
qiime feature-table group \
	--i-table sponge-feature-table.qza \
	--p-axis feature \
	--m-metadata-file node-map.qza \
	--m-metadata-column COMMUNITY \
	--p-mode sum \
	--o-grouped-table grouped-table.qza
```

**Comment by BenKaehler** [comment]
Fixed by 5861232
